AWSTemplateFormatVersion: 2010-09-09
Parameters:
  buildBucketName:
    Type: String
  buildObjectKey:
    Type: String
Resources:
  AddConnectFourMatch:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: Portfolio.Backend.Lambda::Portfolio.Backend.Lambda.ConnectFour.ConnectFourFunctions::AddConnectFourMatch
      Runtime: "dotnetcore2.1"
      Code:
        S3Bucket: !Ref buildBucketName
        S3Key: !Ref buildObjectKey
      Timeout: 30
      Role: !ImportValue AddConnectFourMatchRole
  AddConnectFourMatchPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:invokeFunction'
      FunctionName: !Sub "${AddConnectFourMatch.Arn}"
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${PortfolioApi}/*"
  PortfolioApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: Portfolio API
      FailOnWarnings: true